# Generated by Django 4.2.7 on 2024-02-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipauthormusician",
            name="start",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
